site_name: Vizmaster AI API Documentation
site_url : https://mydomain.org/mysite

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - offline
  - neoteroi.mkdocsoad:
      use_pymdownx: true

nav:
  - Home: index.md
  - Company Management:
    - Company Onboard: company/company.md
    - Company User Management: company-register/company-register.md
  - Admin Management:
    - Admin Onboard : admin-register/admin-register.md
    - Super Admin, Admin Manage: admin-manage/admin-manage.md
  - User Management:
    - Users : user/user.md
    - Users Manage: user-manage/user-manage.md
  - DB Connection : db-connect/db-connect.md
  - OAuth : oauth/oauth.md
  # - example: example/example.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/mkdocsoad.css

