site_name: VizMaster AI API Documentation
site_url : https://mydomain.org/mysite

theme:
  name: material

plugins:
  - search
  - offline
  - neoteroi.mkdocsoad:
      use_pymdownx: true

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/mkdocsoad.css

