openapi: 3.0.0
info:
  title: GenAI-Vizmaster
  version: 1.0.0
  contact:
    name: Gleecus
    url: https://www.gleecus.com/contact-us/
    email: hello@gleecus.com

paths:
  manage_users/self_update_profile/{user_uid}/:
    put:
      tags:
        - User Manage
      summary: Company User Self Update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+7@gleecus.com
                first_name: Hajera
                last_name: Nkhan
                company_uid: 16ab928a-dfbc-41b5-97c2-b52b7d849b8a
                username: Hajera7
                profile: >-
                  https://vizmaster-user-bucket.s3.amazonaws.com/users/33cc53c2-d272-4d7b-906f-34d1c86cf4ad/akrales_190424_3301_0426.jpg
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1NTIxNDM5LCJpYXQiOjE3MjU1MTc4MzksImp0aSI6ImQ4MDI4ZWUwMzIyYjQxZGVhZGMwZjhkYjA3ZmU0M2YwIiwidXNlcl9pZCI6MTR9._3kYdsDKRvoW7u4_uJOFMkGGhd4YANc6YTjed5aknoo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin User Manage
      summary: Admin User Self GET
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1NTIxNDM5LCJpYXQiOjE3MjU1MTc4MzksImp0aSI6ImQ4MDI4ZWUwMzIyYjQxZGVhZGMwZjhkYjA3ZmU0M2YwIiwidXNlcl9pZCI6MTR9._3kYdsDKRvoW7u4_uJOFMkGGhd4YANc6YTjed5aknoo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}