openapi: 3.0.0
info:
  title: Vizmaster AI
  version: 1.0.0


paths:
  manage_users/user_update_by_admin/:
    put:
      tags:
        - Admin User Manage
      summary: Admin User Update By SuperAdmin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                admin_uid: d397a43b-be59-44bb-9d33-e0bb81c8592e
                email: hajera+1@gleecus.com
                first_name: Hajera
                last_name: Nk
                role_name: DataAnalyst
                company_uid: 16ab928a-dfbc-41b5-97c2-b52b7d849b8a
                username: Hajera1
                company_user_uid: 33cc53c2-d272-4d7b-906f-34d1c86cf4ad
                status: active
                user_type: Application
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          description: Authorization Token
        - name: email
          in: body
          schema:
            type: string
          description: User Email address
        - name: first_name
          in: body
          schema:
            type: string
            nullable: true
          description: User First name
        - name: last_name
          in: body
          schema:
            type: string
            nullable: true
          description: User Last name
        - name: role_name
          in: body
          schema:
            type: string
          description: User role in company <br> [Eg:- Data Analyst]
        - name: username
          in: body
          schema:
            type: string
          description: Username
        - name: status
          in: body
          schema:
            type: string
          description: User status <br> active/inactive
        - name: company_user_uid
          in: body
          schema:
            type: string
          description: UUID of Company <br> user whose data <br> should be updated
        - name: company_uid
          in: body
          schema:
            type: string
          description: UUID of User company
        - name: admin_uid
          in: body
          schema:
            type: string
          description: UUID of admin <br> performing the <br> update
        - name: user_type
          in: body
          schema:
            type: string
          description: Type of user <br>[Application]<br>[Administrator]
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  users/adminstrator/:
    post:
      tags:
        - Admin User Manage
      summary: Admin Create By SuperAdmin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+5@gleecus.com
                password: Gleecus123
                role_name: DataEngineers
                company: '1'
                is_data_engineers: true
                is_data_analysts: false
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0ODMwMzA2LCJpYXQiOjE3MjQ4MjY3MDYsImp0aSI6ImQ2MTI5ZTJkMjM5NDQwNWU5YmQxZGRkY2MzYWRlYzY5IiwidXNlcl9pZCI6Mn0.bSWi4bcpiLc0hC1A2Tq2iXSWyH6G6mK9Uys1BgWjCoU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  manage_users/self_update_admin_profile/33cc53c2-d272-4d7b-906f-34d1c86cf4ad/:
    put:
      tags:
        - Admin User Manage
      summary: Admin User Self Update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+7@gleecus.com
                first_name: Hajera
                last_name: Nkhan
                username: Hajera7
                profile: >-
                  https://vizmaster-user-bucket.s3.amazonaws.com/users/33cc53c2-d272-4d7b-906f-34d1c86cf4ad/akrales_190424_3301_0426.jpg
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1NTIxNDM5LCJpYXQiOjE3MjU1MTc4MzksImp0aSI6ImQ4MDI4ZWUwMzIyYjQxZGVhZGMwZjhkYjA3ZmU0M2YwIiwidXNlcl9pZCI6MTR9._3kYdsDKRvoW7u4_uJOFMkGGhd4YANc6YTjed5aknoo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  manage_users/user_profile_upload/:
    post:
      tags:
        - Admin User Manage
      summary: Profile Image Upload Admin User
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                admin_uid:
                  type: string
                  example: 33cc53c2-d272-4d7b-906f-34d1c86cf4ad
                user_profile:
                  type: string
                  format: binary
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1ODg4NjM0LCJpYXQiOjE3MjU4ODUwMzQsImp0aSI6Ijc5ODU3YWI4ZjhjMzRhMWU5YzJiMWFiNmE1YjZlZThmIiwidXNlcl9pZCI6MjF9.SUkLVxsb8UGOYamY81oMxDENrOb3tWGGlQ6oazRCe4I
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  users/admin_user/:
    get:
      tags:
        - Admin User Manage
      summary: Get all Admin users
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              schema:
                type: object
                example: 
                  "id": 2
                  "user_auth": 
                    "id": 4
                    "email": "hajera+5@gleecus.com"
                    "role_name": "Admin"
                    "status": "active"
                    "uuid": "0181d85c-3506-468b-b94b-90413689beb3"
                    "user_type": "Administrator"
                    "username": "HajeraAdmin"
                    "is_active": true
                  "uuid": "6e49143b-0daf-4e9c-bc84-cb515110dd37"
                  "username": "HajeraAdmin"
                  "first_name": null
                  "last_name": null
                  "role_name": "Admin"
                  "profile": null
                  "phone_number": null
                  "created_at": "2024-10-10T06:23:39.256895Z"
                  "updated_at": "2024-10-10T06:23:39.256895Z"
                  "created_by": "d397a43b-be59-44bb-9d33-e0bb81c8592e"
                  "updated_by": "d397a43b-be59-44bb-9d33-e0bb81c8592e"
                  "user": 4
        
        '401':
          description: UnAuthorized
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "Authentication credentials were not provided."
        
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "You do not have permission to perform this action."

        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "Resource not found"