openapi: 3.0.0
info:
  title: Vizmaster AI
  version: 1.0.0
  description: |
    <p style="color: red;"> 🚩 This Section APIs are not finalized and may not be fully functional.</p>

paths:
  dbs/connection:
    get:
      tags:
        - DB Connection
      summary: Get All DbConnection
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  dbs/connection/:
    post:
      tags:
        - DB Connection
      summary: Create DbConnection
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                hostname_ip: localhost
                port: '5436'
                db_name: vizdb
                authentication: ''
                db_username: vizuser
                db_paswd: Gleecus123
                database_type: postgresql
                created_by: ae1c6700-13da-4ae9-8842-902b6113e810
                updated_by: ae1c6700-13da-4ae9-8842-902b6113e810
                company: 1
                company_user: 5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  dbs/connector/:
    post:
      tags:
        - DB Connection
      summary: Create S3-DbConnector
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                connector_json:
                  - aws_secret_key_id: ''
                    aws_secret_access_key: ''
                    region_name: ap-south-1
                    bucket_name: gtl-genai-dbt
                database_type: s3
                created_by: ae1c6700-13da-4ae9-8842-902b6113e810
                updated_by: ae1c6700-13da-4ae9-8842-902b6113e810
                company: 1
                company_user: 5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  dbs/fetch_data_from_datasource/:
    post:
      tags:
        - DB Connection
      summary: Get/Fetch Data From S3-Datasource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                database_type: s3
                company_id: 1
                sql_query: what are the blood types in healthcare data
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  dbs/connect_disconnect_datasource/:
    post:
      tags:
        - DB Connection
      summary: ConnectOrDisconnect Data From Datasource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                database_type: postgresql
                company_id: 1
                connection: disconnect
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}