openapi: 3.0.0
info:
  title: GenAI-Vizmaster
  version: 1.0.0
  contact:
    name: Gleecus
    url: https://www.gleecus.com/contact-us/
    email: hello@gleecus.com

paths:
  users/administer/register/:
    post:
      tags:
        - Administrator Registration
      summary: Vizmaster Admin-User Creation/Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+5@gleecus.com
                password1: Gleecus123
                password2: Gleecus123
                role_name: Admin
                username: HajeraAdmin
                user_type: Administrator
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer IVjqAcn0oLa9LcsXcrlUxmVbAHdTZQ
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/InitializeUploadOutput"
            application/json:
              schema:
                $ref: "#/components/schemas/InitializeUploadOutput"
            text/json:
              schema:
                $ref: "#/components/schemas/InitializeUploadOutput"