openapi: 3.0.0
info:
  title: Vizmaster AI
  version: 1.0.0

paths:  
  /oauth2/token/:
      post:
        tags:
          - Oauth2 Grant Token
        summary: Oauth Grant Token
        requestBody:
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  client_id:
                    type: string
                    example: 2rKPFJjwhNYbgTyE1XfByWXDy8bozmXQLPgDWxnr
                  client_secret:
                    type: string
                    example: >-
                      mLAWYVAqn3Ov6LA4QhJP9T4BCUOGpHv8Z5XiKbojBkmJEdQsfAd0IqNL9P8t4F4FLod3zJf3J2QUsQ64cdPliJUtEv8wu7tc7NPajEEtvI5bOnecm0EdmJrrmXhsijG0
                  grant_type:
                    type: string
                    example: client_credentials
        responses:
          '200':
            description: Successful response
            content:
              application/json: {}