openapi: 3.0.0
info:
  title: Vizmaster AI
  version: 1.0.0

paths:
  users/auth/password_reset:
    post:
      tags:
        - Password Manage
      summary: User Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+5@gleecus.com
                password: Gleecus123
                role_name: DataEngineers
                company: '1'
                is_data_engineers: true
                is_data_analysts: false
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0ODMwMzA2LCJpYXQiOjE3MjQ4MjY3MDYsImp0aSI6ImQ2MTI5ZTJkMjM5NDQwNWU5YmQxZGRkY2MzYWRlYzY5IiwidXNlcl9pZCI6Mn0.bSWi4bcpiLc0hC1A2Tq2iXSWyH6G6mK9Uys1BgWjCoU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  
  users/auth/password_change_by_admin/:
    post:
      tags:
        - Password Manage
      summary: User Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+5@gleecus.com
                password: Gleecus123
                role_name: DataEngineers
                company: '1'
                is_data_engineers: true
                is_data_analysts: false
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0ODMwMzA2LCJpYXQiOjE3MjQ4MjY3MDYsImp0aSI6ImQ2MTI5ZTJkMjM5NDQwNWU5YmQxZGRkY2MzYWRlYzY5IiwidXNlcl9pZCI6Mn0.bSWi4bcpiLc0hC1A2Tq2iXSWyH6G6mK9Uys1BgWjCoU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  users/auth/password_change/:
    post:
      tags:
        - Password Manage
      summary: User Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+5@gleecus.com
                password: Gleecus123
                role_name: DataEngineers
                company: '1'
                is_data_engineers: true
                is_data_analysts: false
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0ODMwMzA2LCJpYXQiOjE3MjQ4MjY3MDYsImp0aSI6ImQ2MTI5ZTJkMjM5NDQwNWU5YmQxZGRkY2MzYWRlYzY5IiwidXNlcl9pZCI6Mn0.bSWi4bcpiLc0hC1A2Tq2iXSWyH6G6mK9Uys1BgWjCoU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}