openapi: 3.0.0
info:
  title: GenAI-Vizmaster
  version: 1.0.0
  contact:
    name: Gleecus
    url: https://www.gleecus.com/contact-us/
    email: hello@gleecus.com

paths:
  users/company/admin/register/:
    post:
      tags:
        - Company User Registration
      summary: Vizmaster App Admin-User Creation/Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+1@gleecus.com
                password1: Gleecus123
                password2: Gleecus123
                role_name: AppSuperAdmin
                username: Hajera1
                company: Gleecus Tech
                user_type: Application
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  users/company/user/register/:
    post:
      tags:
        - Company User Registration
      summary: Vizmaster User Creation/Registration Copy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+9@gleecus.com
                password1: Gleecus123
                password2: Gleecus123
                role_name: DataEngineer
                company: '1'
                username: Hajera9
                user_type: Application
                first_name: ''
                last_name: ''
                profile: ''
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1NTI3NTg1LCJpYXQiOjE3MjU1MjM5ODUsImp0aSI6ImJjNzEzNmRjNThkMzQxYmZiZTNlMTExNjUyNmE2ZDc4IiwidXNlcl9pZCI6MTR9.Dj0byug07ErDYmNbeVCGTcVhylHSn4fn9SekkNMqox8
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}