openapi: 3.0.0
info:
  title: Vizmaster AI
  version: 1.0.0

paths:
  users/company_user/:
    put:
      tags:
        - User Manage
      summary: User Create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+5@gleecus.com
                password: Gleecus123
                role_name: DataEngineers
                company: '1'
                is_data_engineers: true
                is_data_analysts: false
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0ODMwMzA2LCJpYXQiOjE3MjQ4MjY3MDYsImp0aSI6ImQ2MTI5ZTJkMjM5NDQwNWU5YmQxZGRkY2MzYWRlYzY5IiwidXNlcl9pZCI6Mn0.bSWi4bcpiLc0hC1A2Tq2iXSWyH6G6mK9Uys1BgWjCoU
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type:object:
                example: {}
                 

    get:
      tags:
        - User Manage
      summary: Retrieve all company users
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1NTE3MjE1LCJpYXQiOjE3MjU1MTM2MTUsImp0aSI6IjM0M2ZjZDU5NDYyZTRhMjhhY2FjNjYzNzJjYmRiMmU0IiwidXNlcl9pZCI6MTR9.D49XkmXeva4xS4ti1uV48iXuQyUKr__4JX2P9hcMfx0
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              schema:
                type: object
                example:
                  "id": 3
                  "company_details": 
                    "id": 2
                    "status": "active"
                    "uuid": "d6e4cb91-e58a-4e75-86e8-1e98659fcac1"
                    "name": "Glcs-12"
                    "address": "abcd roadno-123"
                    "phone_number": ""
                    "logo": ""
                    "slug": "glcs-12"
                    "created_by": "435ea0ee-1e8f-4031-a5e3-948923ec7003"
                    "updated_by": "435ea0ee-1e8f-4031-a5e3-948923ec7003"
                    "created_at": "2024-10-18T11:57:18.377560Z"
                    "updated_at": "2024-10-18T11:57:18.377580Z"
                  "user_auth": 
                    "id": 43
                    "email": "bhanu+78@gleecus.com"
                    "role_name": "DataAnalyst"
                    "status": "active"
                    "uuid": "7b5ae106-b67e-49d9-b288-ecd0e76f88dd"
                    "user_type": "Application"
                    "username": "bhanu78"
                    "is_active": true
                
                  "uuid": "7d6c976a-5a4d-4b5a-a79c-a6eed861a744"
                  "username": "bhanu78"
                  "first_name": ""
                  "last_name": ""
                  "role_name": "DataAnalyst"
                  "profile": ""
                  "phone_number": null
                  "created_at": "2024-10-22T13:23:31.237002Z"
                  "updated_at": "2024-10-22T13:23:31.237009Z"
                  "created_by": "2a633329-f840-4039-9887-38e45c87a054"
                  "updated_by": "2a633329-f840-4039-9887-38e45c87a054"
                  "created_by_group": "Administrator"
                  "updated_by_group": "Administrator"
                  "user": 43
                  "company": 2

  manage_users/user_update_by_admin/:
    put:
      tags:
        - User Manage
      summary: Update user details by admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                admin_uid: d397a43b-be59-44bb-9d33-e0bb81c8592e
                email: hajera+1@gleecus.com
                first_name: Hajera
                last_name: Nk
                role_name: DataAnalyst
                company_uid: 16ab928a-dfbc-41b5-97c2-b52b7d849b8a
                username: Hajera1
                company_user_uid: 33cc53c2-d272-4d7b-906f-34d1c86cf4ad
                status: active
                user_type: Application
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          description: Authorization Token
        - name: email
          in: body
          schema:
            type: string
          description: User Email address
        - name: first_name
          in: body
          schema:
            type: string
            nullable: true
          description: User First name
        - name: last_name
          in: body
          schema:
            type: string
            nullable: true
          description: User Last name
        - name: role_name
          in: body
          schema:
            type: string
          description: User role in company <br> [Eg:- Data Analyst]
        - name: username
          in: body
          schema:
            type: string
          description: Username
        - name: status
          in: body
          schema:
            type: string
          description: User status <br> active/inactive
        - name: company_user_uid
          in: body
          schema:
            type: string
          description: UUID of Company <br> user whose data <br> should be updated
        - name: company_uid
          in: body
          schema:
            type: string
          description: UUID of User company
        - name: admin_uid
          in: body
          schema:
            type: string
          description: UUID of admin <br> performing the <br> update
        - name: user_type
          in: body
          schema:
            type: string
          description: Type of user <br>[Application]<br>[Administrator]
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              schema:
                type: object
                example:
                  message: "User details updated."
       
        '400':
          description: Wrong credentials
          content:
            application/json: 
              schema:
                type: object
                example:
                  message: "User with given updated_by-cfeb3f7f-0a57-42e2-9340-c028cd151652 doesnot exists!"

        '401':
          description: UnAuthorized
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "Authentication credentials were not provided."

        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "You do not have permission to perform this action."
        
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "Resource not found"

        '405':
          description: Method not allwoed
          content:
            application/json:
              schema:
                type: object
                example:
                  "message": "Method \"GET\" not allowed."    

  manage_users/self_update_profile/{user_uid}/:
    put:
      tags:
        - User Manage
      summary: Update own profile with `user_uid`
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+7@gleecus.com
                first_name: Hajera
                last_name: Nkhan
                company_uid: 16ab928a-dfbc-41b5-97c2-b52b7d849b8a
                username: Hajera7
                profile: >-
                  https://vizmaster-user-bucket.s3.amazonaws.com/users/33cc53c2-d272-4d7b-906f-34d1c86cf4ad/akrales_190424_3301_0426.jpg
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          description: Authorization Token
        - name: user_uid
          in: URL
          schema:
            type: string
          description: User UUID for profile<br>update
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - User Manage
      summary: Retrieve own profile details using `user_uid`
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          description: Authorization Token
        - name: user_uid
          in: URL
          schema:
            type: string
          description: User UUID for<br>fetching details

      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  manage_users/user_profile_upload/:
    post:
      tags:
        - User Manage
      summary: Company user profile image upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_uid:
                  type: string
                  example: 33cc53c2-d272-4d7b-906f-34d1c86cf4ad
                user_profile:
                  type: string
                  format: binary
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              schema:
                type: object
                example: {}
  
  
  manage_users/users_delete_by_admins/:
    post:
      tags:
        - User Manage
      summary: Delete company users by admin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company_user_uids:
                  - 2264e2ff-5ffc-4921-b8be-6a81f62aa7d4
                company_uid: 16ab928a-dfbc-41b5-97c2-b52b7d849b8a
                admin_user_type: Application
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  manage_users/update_user_status_by_admins/:
    post:
      tags:
        - User Manage
      summary: Change status of specified company users by admins
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company_user_uids:
                  - ae1c6700-13da-4ae9-8842-902b6113e810
                  - 33cc53c2-d272-4d7b-906f-34d1c86cf4ad
                company_uid: 16ab928a-dfbc-41b5-97c2-b52b7d849b8a
                admin_user_type: Application
                status: active
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
            
  manage_users/email_test/:
    post:
      tags:
        - User Manage
      summary: Email sending test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: hajera+7@gleecus.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  